[project]
name = "eh-validation-eplus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "enerhabitat>=0.2.0",
    "iertools",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "notebook>=7.5.1",
]

[tool.uv.sources]
iertools = { git = "https://github.com/altamarmx/iertools.git" }
